	-- =============================================================================
-- Diagram Name: MODELO_DATOS
-- Created on: 24/08/2014 10:43:51 a. m.
-- Diagram Version: 
-- =============================================================================

CREATE SCHEMA "Schema0";


CREATE TABLE "SGI_NIVE_FORM" (
	"NIV_CODI" SMALLSERIAL NOT NULL,
	"NIV_NOMB" varchar(45),
	PRIMARY KEY("NIV_CODI")
);

CREATE TABLE "SGI_NIVE_INVE" (
	"NIN_INV_CODI" int(11) NOT NULL,
	"NIN_NIV_CODI" int(11) NOT NULL,
	"NIN_TITU_OBTE" varchar(100)  NULL,
	"NIN_INST" varchar(100) NULL,
	"NIN_AGNO" int(5) NULL,
	PRIMARY	KEY("NIN_INV_CODI","NIN_NIV_CODI")
);

CREATE TABLE "SGI_GRUP" (
	"GRU_CODI_COLC" varchar(20) NOT NULL,
	"GRU_NOMB" varchar(45),
	"GRU_MESS_CODI" int2 NOT NULL,
	"GRU_AREA_CODI" int2 NOT NULL,
	"GRU_AGNO_CODI" int2 NOT NULL,
	"GRU_CENT_CODI" int2 NOT NULL,
	PRIMARY KEY("GRU_CODI_COLC")
);

CREATE TABLE "SGI_AGNO" (
	"AGN_CODI" SMALLSERIAL NOT NULL,
	"AGN_DESC" varchar(4) NOT NULL,
	PRIMARY KEY("AGN_CODI")
);

CREATE TABLE "SGI_MESS" (
	"MES_CODI" SMALLSERIAL NOT NULL,
	"MES_NOMB" varchar(20) NOT NULL,
	PRIMARY KEY("MES_CODI")
);

CREATE TABLE "SGI_AREA" (
	"ARE_CODI" SMALLSERIAL NOT NULL,
	"ARE_NOMB" varchar(45) NOT NULL,
	"ARE_GRAN_AREA_CODI" int2 NOT NULL,
	PRIMARY KEY("ARE_CODI")
);

CREATE TABLE "SGI_GRAN_AREA" (
	"GAR_CODI" SMALLSERIAL NOT NULL,
	"GAR_NOMB" varchar(45) NOT NULL,
	PRIMARY KEY("GAR_CODI")
);

CREATE TABLE "SGI_INVE" (
	"INV_CODI" int(11) NOT NULL, 
	"INV_IDEN" varchar(20) NOT NULL,
	"INV_TIPO_DOCU_CODI" int2 NOT NULL,
	"INV_NOMB" varchar(25) NOT NULL,
	"INV_APEL" varchar(25) NOT NULL,
	"INV_LINK_CVLA" varchar(45) NOT NULL,
	"INV_FECH_NACI" date NOT NULL,
	"INV_CENT_CODI" int2 NOT NULL,
	"INV_PROG_ACAD_CODI" int2 NOT NULL,
	"INV_MAIL" varchar(30),
	"INV_TELE_CELU" varchar(20),
	PRIMARY KEY("INV_IDEN")
);

CREATE TABLE "SGI_INVE_GRUP" (
	"IGR_CODI" SERIAL NOT NULL,
	"IGR_INVE_IDEN" varchar(20) NOT NULL,
	"IGR_GRUP_CODI_COLC" varchar(20) NOT NULL,
	"IGR_FECH_INIC" date,
	"IGR_FECH_TERM" date,
	"IGR_TIPO_VINC_CODI" int2 NOT NULL,
	PRIMARY KEY("IGR_CODI")
);

CREATE TABLE "SGI_TIPO_VINC" (
	"TIV_CODI" SMALLSERIAL NOT NULL,
	"TIV_DESC" varchar(45) NOT NULL,
	PRIMARY KEY("TIV_CODI")
);

CREATE TABLE "SGI_SEMI" (
	"SEM_CODI" SERIAL NOT NULL,
	"SEM_NOMB" varchar(45) NOT NULL,
	"SEM_MISI" text,
	"SEM_VISI" text,
	"SEM_OBJG" text,
	"SEM_TEMA_INVE" text,
	"SEM_PRPR_ESPE" text,
	"SEM_OBJE" text,
	"SEM_PROP_ACTU" bytea,
	"SEM_PERT_CADE" text,
	"SEM_ARTI_LINE" text,
	"SEM_PROY_REGI" text,
	"SEM_ESTR_FINA" text,
	"SEM_ESTR_KNOW" text,
	"SEM_ESTR_ELAB_PROD" text,
	"SEM_ESTR_EXTE" text,
	"SEM_ESTR_VINC_ESTU" text,
	"SEM_ALIA_CONV" text,
	"SEM_CENT_CODI" int2 NOT NULL,
	PRIMARY KEY("SEM_CODI")
);

CREATE TABLE "SGI_LINE_INVE" (
	"LIN_CODI" SMALLSERIAL NOT NULL,
	"LIN_DESC" varchar(45) NOT NULL,
	PRIMARY KEY("LIN_CODI")
);

CREATE TABLE "SGI_LINE_INVE_SEMI" (
	"LIS_CODI" SMALLSERIAL NOT NULL,
	"LIS_SEMI_CODI" int4 NOT NULL,
	"LIS_LINE_INVE_CODI" int2 NOT NULL,
	PRIMARY KEY("LIS_CODI")
);

CREATE TABLE "SGI_GRUP_LINE_INVE" (
	"GLI_CODI" SMALLSERIAL NOT NULL,
	"GLI_GRUP_CODI_COLC" varchar(20) NOT NULL,
	"GLI_LINE_INVE_CODI" int2 NOT NULL,
	PRIMARY KEY("GLI_CODI")
);

CREATE TABLE "SGI_PROG_ACAD" (
	"PAC_CODI" SMALLSERIAL NOT NULL,
	"PAC_NOMB" varchar(45) NOT NULL,
	"PAC_ESCU_CODI" int2 NOT NULL,
	PRIMARY KEY("PAC_CODI")
);

CREATE TABLE "SGI_PROG_ACAD_SEMI" (
	"PAS_CODI" SMALLSERIAL NOT NULL,
	"PAS_PROG_ACAD_CODI" int2 NOT NULL,
	"PAS_SEMI_CODI" int4 NOT NULL,
	"PAS_FECH_INIC" date,
	"PAS_FECH_TERM" date,
	PRIMARY KEY("PAS_CODI")
);

CREATE TABLE "SGI_GRUP_PROG_ACAD" (
	"GPA_CODI" SMALLSERIAL NOT NULL,
	"GPA_GRUP_CODI_COLC" varchar(20) NOT NULL,
	"GPA_PROG_ACAD_CODI" int2 NOT NULL,
	PRIMARY KEY("GPA_CODI")
);

CREATE TABLE "SGI_SEMI_GRUP" (
	"SGR_CODI" SMALLSERIAL NOT NULL,
	"SGR_SEMI_CODI" int4 NOT NULL,
	"SGR_GRUP_CODI_COLC" varchar(20) NOT NULL,
	"SGR_FECH_INIC" date,
	"SGR_FECH_TERM" date,
	PRIMARY KEY("SGR_CODI")
);

CREATE TABLE "SGI_ESCU" (
	"ESC_CODI" SMALLSERIAL NOT NULL,
	"ESC_NOMB" varchar(45) NOT NULL,
	"ESC_SIGL" varchar(20),
	PRIMARY KEY("ESC_CODI")
);

CREATE TABLE "SGI_INVE_SEMI" (
	"INS_CODI" SERIAL NOT NULL,
	"INS_INVE_IDEN" varchar(20) NOT NULL,
	"INS_SEMI_CODI" int4 NOT NULL,
	"INS_FECH_INIC" date,
	"INS_FECH_TERM" date,
	"INS_TIPO_VINC_CODI" int2 NOT NULL,
	PRIMARY KEY("INS_CODI")
);

CREATE TABLE "SGI_CENT" (
	"CEN_CODI" SMALLSERIAL NOT NULL,
	"CEN_NOMB" varchar(25),
	"CEN_ZONA_CODI" int2 NOT NULL,
	PRIMARY KEY("CEN_CODI")
);

CREATE TABLE "SGI_ZONA" (
	"ZON_CODI" SMALLSERIAL NOT NULL,
	"ZON_NOMB" varchar(25) NOT NULL,
	"ZON_SIGL" varchar(10) NOT NULL,
	PRIMARY KEY("ZON_CODI")
);

CREATE TABLE "SGI_TIPO_DOCU" (
	"TID_CODI" SMALLSERIAL NOT NULL,
	"TID_NOMB" varchar(20) NOT NULL,
	PRIMARY KEY("TID_CODI")
);

CREATE TABLE "SGI_PROY" (
	"PRO_IDEN" SMALLSERIAL NOT NULL,
	"PRO_NOMB" varchar(60) NOT NULL,
	PRIMARY KEY("PRO_IDEN")
);

CREATE TABLE "SGI_GRUP_PROY" (
	"GPR_CODI" SMALLSERIAL NOT NULL,
	"GPR_GRUP_CODI_COLC" varchar(20) NOT NULL,
	"GPR_PROY_IDEN" int2 NOT NULL,
	PRIMARY KEY("GPR_CODI")
);

CREATE TABLE "SGI_SEMI_PROY" (
	"SEP_IDEN" SMALLSERIAL NOT NULL,
	"SEP_SEMI_CODI" int4 NOT NULL,
	"SEP_PROY_IDEN" int2 NOT NULL,
	PRIMARY KEY("SEP_IDEN")
);

CREATE TABLE "SGI_CONV" (
	"CON_CODI" int4 NOT NULL,
	"CON_NUME" int4 NOT NULL,
	"CON_DESC" varchar(45) NOT NULL,
	"CON_TEXT" bytea,
	"CON_FECH_INIC" date,
	"CON_FECH_FINA" date,
	"CON_TIPO_CONV_CODI" int4 NOT NULL,
	PRIMARY KEY("CON_CODI")
);

CREATE TABLE "SGI_TIPO_CONV" (
	"TCO_CODI" SERIAL NOT NULL,
	"TCO_DESC" int4 NOT NULL,
	PRIMARY KEY("TCO_CODI")
);

CREATE TABLE "SGI_SEMI_CONV" (
	"SCO_CODI" SERIAL NOT NULL,
	"SCO_SEMI_CODI" int4 NOT NULL,
	"SCO_CONV_CODI" int4 NOT NULL,
	PRIMARY KEY("SCO_CODI")
);

CREATE TABLE "SGI_GRUP_CONV" (
	"GCO_CODI" SERIAL NOT NULL,
	"GCO_GRUP_CODI_COLC" varchar(20) NOT NULL,
	"GCO_CONV_CODI" int4 NOT NULL,
	PRIMARY KEY("GCO_CODI")
);


ALTER TABLE "SGI_GRUP" ADD CONSTRAINT "SGI_GRUP_MESS" FOREIGN KEY ("GRU_MESS_CODI")
	REFERENCES "SGI_MESS"("MES_CODI")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "SGI_GRUP" ADD CONSTRAINT "SGI_GRUP_AREA" FOREIGN KEY ("GRU_AREA_CODI")
	REFERENCES "SGI_AREA"("ARE_CODI")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "SGI_GRUP" ADD CONSTRAINT "SGI_GRUP_AGNO" FOREIGN KEY ("GRU_AGNO_CODI")
	REFERENCES "SGI_AGNO"("AGN_CODI")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "SGI_GRUP" ADD CONSTRAINT "Ref_SGI_GRUP_to_SGI_CENT" FOREIGN KEY ("GRU_CENT_CODI")
	REFERENCES "SGI_CENT"("CEN_CODI")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "SGI_AREA" ADD CONSTRAINT "SGI_AREA_GRAN_AREA" FOREIGN KEY ("ARE_GRAN_AREA_CODI")
	REFERENCES "SGI_GRAN_AREA"("GAR_CODI")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "SGI_INVE" ADD CONSTRAINT "Ref_SGI_INVE_to_SGI_CENT" FOREIGN KEY ("INV_CENT_CODI")
	REFERENCES "SGI_CENT"("CEN_CODI")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "SGI_INVE" ADD CONSTRAINT "Ref_SGI_INVE_to_SGI_TIPO_DOCU" FOREIGN KEY ("INV_TIPO_DOCU_CODI")
	REFERENCES "SGI_TIPO_DOCU"("TID_CODI")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "SGI_INVE" ADD CONSTRAINT "Ref_SGI_INVE_to_SGI_PROG_ACAD" FOREIGN KEY ("INV_PROG_ACAD_CODI")
	REFERENCES "SGI_PROG_ACAD"("PAC_CODI")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "SGI_INVE_GRUP" ADD CONSTRAINT "SGI_INVE_GRUP_INVE" FOREIGN KEY ("IGR_INVE_IDEN")
	REFERENCES "SGI_INVE"("INV_IDEN")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "SGI_INVE_GRUP" ADD CONSTRAINT "SGI_INVE_GRUP_GRUP" FOREIGN KEY ("IGR_GRUP_CODI_COLC")
	REFERENCES "SGI_GRUP"("GRU_CODI_COLC")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "SGI_INVE_GRUP" ADD CONSTRAINT "SGI_INVE_TIPO_VINC" FOREIGN KEY ("IGR_TIPO_VINC_CODI")
	REFERENCES "SGI_TIPO_VINC"("TIV_CODI")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "SGI_SEMI" ADD CONSTRAINT "Ref_SGI_SEMI_to_SGI_CENT" FOREIGN KEY ("SEM_CENT_CODI")
	REFERENCES "SGI_CENT"("CEN_CODI")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "SGI_LINE_INVE_SEMI" ADD CONSTRAINT "SGI_LINE_INVE_SEMI_LINE_INVE" FOREIGN KEY ("LIS_LINE_INVE_CODI")
	REFERENCES "SGI_LINE_INVE"("LIN_CODI")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "SGI_LINE_INVE_SEMI" ADD CONSTRAINT "SGI_LINE_INVE_SEMI_SEMI" FOREIGN KEY ("LIS_SEMI_CODI")
	REFERENCES "SGI_SEMI"("SEM_CODI")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "SGI_GRUP_LINE_INVE" ADD CONSTRAINT "SGI_GRUP_LINE_INVE_GRUP" FOREIGN KEY ("GLI_GRUP_CODI_COLC")
	REFERENCES "SGI_GRUP"("GRU_CODI_COLC")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "SGI_GRUP_LINE_INVE" ADD CONSTRAINT "SGI_GRUP_LINE_INVE_LINE_INVE" FOREIGN KEY ("GLI_LINE_INVE_CODI")
	REFERENCES "SGI_LINE_INVE"("LIN_CODI")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "SGI_PROG_ACAD" ADD CONSTRAINT "Ref_SGI_PROG_ACAD_to_SGI_ESCU" FOREIGN KEY ("PAC_ESCU_CODI")
	REFERENCES "SGI_ESCU"("ESC_CODI")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "SGI_PROG_ACAD_SEMI" ADD CONSTRAINT "SGI_PROG_ACAD_SEMI_PROG_ACAD" FOREIGN KEY ("PAS_PROG_ACAD_CODI")
	REFERENCES "SGI_PROG_ACAD"("PAC_CODI")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "SGI_PROG_ACAD_SEMI" ADD CONSTRAINT "SGI_PROG_ACAD_SEMI_SEMI" FOREIGN KEY ("PAS_SEMI_CODI")
	REFERENCES "SGI_SEMI"("SEM_CODI")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "SGI_GRUP_PROG_ACAD" ADD CONSTRAINT "SGI_GRUP_PROG_ACAD_GRUP" FOREIGN KEY ("GPA_GRUP_CODI_COLC")
	REFERENCES "SGI_GRUP"("GRU_CODI_COLC")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "SGI_GRUP_PROG_ACAD" ADD CONSTRAINT "SGI_GRUP_PROG_ACAD_PROG_ACAD" FOREIGN KEY ("GPA_PROG_ACAD_CODI")
	REFERENCES "SGI_PROG_ACAD"("PAC_CODI")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "SGI_SEMI_GRUP" ADD CONSTRAINT "Ref_SGI_SEMI_has_SGI_GRUP_to_SGI_SEMI" FOREIGN KEY ("SGR_SEMI_CODI")
	REFERENCES "SGI_SEMI"("SEM_CODI")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "SGI_SEMI_GRUP" ADD CONSTRAINT "SGI_SEMI_GRUP_GRUP" FOREIGN KEY ("SGR_GRUP_CODI_COLC")
	REFERENCES "SGI_GRUP"("GRU_CODI_COLC")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "SGI_INVE_SEMI" ADD CONSTRAINT "Ref_SGI_INVE_has_SGI_SEMI_to_SGI_INVE" FOREIGN KEY ("INS_INVE_IDEN")
	REFERENCES "SGI_INVE"("INV_IDEN")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "SGI_INVE_SEMI" ADD CONSTRAINT "Ref_SGI_INVE_has_SGI_SEMI_to_SGI_SEMI" FOREIGN KEY ("INS_SEMI_CODI")
	REFERENCES "SGI_SEMI"("SEM_CODI")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "SGI_INVE_SEMI" ADD CONSTRAINT "SGI_INVE_SEMI_TIPO_VINC" FOREIGN KEY ("INS_TIPO_VINC_CODI")
	REFERENCES "SGI_TIPO_VINC"("TIV_CODI")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "SGI_CENT" ADD CONSTRAINT "Ref_SGI_CENT_to_SGI_ZONA" FOREIGN KEY ("CEN_ZONA_CODI")
	REFERENCES "SGI_ZONA"("ZON_CODI")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "SGI_GRUP_PROY" ADD CONSTRAINT "Ref_SGI_GRUP_has_SGI_PROY_to_SGI_GRUP" FOREIGN KEY ("GPR_GRUP_CODI_COLC")
	REFERENCES "SGI_GRUP"("GRU_CODI_COLC")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "SGI_GRUP_PROY" ADD CONSTRAINT "Ref_SGI_GRUP_has_SGI_PROY_to_SGI_PROY" FOREIGN KEY ("GPR_PROY_IDEN")
	REFERENCES "SGI_PROY"("PRO_IDEN")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "SGI_SEMI_PROY" ADD CONSTRAINT "Ref_SGI_SEMI_has_SGI_PROY_to_SGI_SEMI" FOREIGN KEY ("SEP_SEMI_CODI")
	REFERENCES "SGI_SEMI"("SEM_CODI")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "SGI_SEMI_PROY" ADD CONSTRAINT "Ref_SGI_SEMI_has_SGI_PROY_to_SGI_PROY" FOREIGN KEY ("SEP_PROY_IDEN")
	REFERENCES "SGI_PROY"("PRO_IDEN")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "SGI_CONV" ADD CONSTRAINT "Ref_SGI_CONV_to_SGI_TIPO_CONV" FOREIGN KEY ("CON_TIPO_CONV_CODI")
	REFERENCES "SGI_TIPO_CONV"("TCO_CODI")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "SGI_SEMI_CONV" ADD CONSTRAINT "Ref_SGI_SEMI_has_SGI_CONV_to_SGI_SEMI" FOREIGN KEY ("SCO_SEMI_CODI")
	REFERENCES "SGI_SEMI"("SEM_CODI")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "SGI_SEMI_CONV" ADD CONSTRAINT "Ref_SGI_SEMI_has_SGI_CONV_to_SGI_CONV" FOREIGN KEY ("SCO_CONV_CODI")
	REFERENCES "SGI_CONV"("CON_CODI")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "SGI_GRUP_CONV" ADD CONSTRAINT "Ref_SGI_GRUP_has_SGI_CONV_to_SGI_GRUP" FOREIGN KEY ("GCO_GRUP_CODI_COLC")
	REFERENCES "SGI_GRUP"("GRU_CODI_COLC")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "SGI_GRUP_CONV" ADD CONSTRAINT "Ref_SGI_GRUP_has_SGI_CONV_to_SGI_CONV" FOREIGN KEY ("GCO_CONV_CODI")
	REFERENCES "SGI_CONV"("CON_CODI")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;


